FROM localhost/kakinari/ubi-micro-ja:10-cs-nodejs
COPY node.sh /etc/profile.d/node.sh
WORKDIR /opt
RUN curl -L https://nodejs.org/dist/latest/node-v26.3.0-linux-x64.tar.gz | tar xzf - && \
    mv node-v26.3.0-linux-x64 node && \
    chmod 777 node && \
    mkdir -p  pnpm && \
    chmod 777 pnpm && \
    source /etc/profile.d/node.sh && \
    curl -fsSL https://get.pnpm.io/install.sh | sh - && \
    pnpm config set store-dir /opt/pnpm/store --global && \
    pnpm config set prefix /opt/pnpm --global
WORKDIR /root
