FROM registry.access.redhat.com/ubi9/ubi-init:latest
ENV ORACLE_DOCKER_INSTALL=true
WORKDIR /root
RUN dnf install -y less vim-minimal hostname glibc-langpack-ja openssl openssh \
oracle-database-preinstall-23ai-1.0-2.el9.x86_64.rpm; \
dnf install -y oracle-database-free-23ai-1.0-1.el9.x86_64.rpm
CMD [ "/sbin/init" ]
