FROM docker.io/kakinari/ubi-micro-ja:9-dev AS devenv
ARG VERSION 3.3.3
RUN curl -O https://cache.ruby-lang.org/pub/ruby/3.3/ruby-${VERSION}.tar.gz; \
tar xvzf ruby-${VERSION}.tar.gz; \
cd ruby-${VERSION}; \
./configure; \
make; \
make install

FROM docker.io/kakinari/ubi-micro-ja:9-dev
COPY --from=devenv /usr/local /usr/local
RUN mkdir /root/work
WORKDIR /root/work
