FROM docker.io/kakinari/ubi-micro-ja:9-java22-dev AS devenv
RUN curl -O https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz; \
tar xvzf apache-jmeter-5.6.3.tgz

FROM docker.io/kakinari/ubi-micro-ja:9-22-jbase
COPY --from=devenv /root/apache-jmeter-5.6.3 /opt/apache-jmeter-5.6.3
ENV container podman
ENV JMETER_HOME /opt/apache-jmeter-5.6.3
CMD [ "/opt/apache-jmeter-5.6.3/bin/jmeter" ]
WORKDIR /root
