FROM registry.redhat.io/ubi10-init:latest
ENV conteiner podman
RUN dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm -y; \
dnf update; \
dnf install glibc-langpack-ja -y; \
dnf groupinstall "Development Tools" -y; \
dnf remove java-1.8.0-openjdk-headless -y; \
dnf install vim-minimal gperf openssl zlib readline gmp libffi libyaml \
openssl-devel zlib-devel readline-devel gmp-devel libffi-devel libyaml-devel \
openssh-clients java-latest-openjdk-devel java-latest-openjdk-jmods -y; \
dnf clean all; \
rm -rf /root/*
ENV LANG ja_JP.UTF-8
ENV TZ JST-9
ENV JAVA_HOME /usr/lib/jvm/java-24-openjdk
WORKDIR "/root"
