FROM localhost/kakinari/ubi-micro-ja:9-dev AS devenv
ARG TARGET=17.4
RUN curl -O https://ftp.postgresql.org/pub/source/v${TARGET}/postgresql-${TARGET}.tar.gz; \
tar xvzf postgresql-${TARGET}.tar.gz; \
cd postgresql-${TARGET}; \
./configure  --with-perl --with-python --with-tcl --with-lz4 --enable-nls="ja" \
 --with-zstd --with-openssl --with-systemd --with-libxml --with-libraries='/usr/lib64'; \
make world; \
make check; \
make install-world;

FROM localhost/kakinari/ubi-micro-ja:9-postgres
COPY --from=devenv /usr/local /usr/local
ENV LD_LIBRARY_PATH /usr/local/pgsql/lib
ENV PGDATA /usr/local/pgsql/data
ENV PGLOGDIR /usr/local/pgsql/log
ENV PATH /usr/local/pgsql/bin:$HOME/.local/bin:$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN adduser postgres; \
mkdir -p /usr/local/pgsql/data; \
mkdir -p /usr/local/pgsql/logs; \
chown -R postgres:postgres /usr/local/pgsql;
USER postgres:postgres
WORKDIR /home/postgres
