FROM localhost/kakinari/ubi-micro-ja:10-nvm
ARG VERSION=v0.40.5
RUN mkdir /root/work; touch /root/.bashrc; \
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/${VERSION}/install.sh | bash
WORKDIR /usr/work
